--- #YAML:1.0
name: Win32-EventLog-Carp
version: 1.33
author: Robert Rothenberg <rrwo at cpan.org>
abstract: for carping in the Windows NT Event Log
license: perl
requires:
  Carp: 0
  Carp::Heavy: 0
  File::Basename: 0
  File::Spec: 0
  Test::More: 0
  Win32: 0
  Win32::EventLog: 0
  perl: 5.005
recommends:
  Win32::EventLog::Message: 0
provides: {}
generated_by: Module::Build version 0.25
