--- #YAML:1.0
name: Win32-EventLog-Carp
version: 1.40
license: perl
distribution_type: module
requires:
  Carp: 0
  Carp::Heavy: 0
  File::Basename: 0
  File::Spec: 0
  Win32: 0
  Win32::EventLog: 0
  perl: 5.005
recommends:
  Win32::EventLog::Message: 0
build_requires:
  Test::More: 0
conflicts: {}
provides:
  Win32::EventLog::Carp:
    file: lib/Win32/EventLog/Carp.pm
    version: 1.40
generated_by: Module::Build version 0.20
